### ISSUE TITLE
师傅您好

### ISSUE THREAD

**Issue by NNanfeng** [Lamber-maybe/lamber-maybe.github.io#1]
您的博客出现了404错误，我想查看您https://www.lamber-maybe.com/posts/Multiplayer-HTB/  这一篇文章，但是已经访问不到了

**Comment by Lamber-maybe** [comment]
> 您的博客出现了404错误，我想查看您https://www.lamber-maybe.com/posts/Multiplayer-HTB/ 这一篇文章，但是已经访问不到了

已经好了，直接从主页进吧，谷歌的索引可能还没更新，换了下博客的框架，目录结构有点发生变化

**Comment by NNanfeng** [comment]
麻烦您了
